version: 2
updates:
  - package-ecosystem: composer
    directory: /bdus-api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      composer-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /bdus-app
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /bdus-docs
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        update-types: [minor, patch]
